<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->delete();
        $books = [
            [
                'title' => 'Lập Trình Laravel Cơ Bản',
                'author' => 'Nguyễn Văn A',
                'price' => 120000,
                'image' => 'books/1.jpg',
                'publication_date' => '2022-03-15',
                'description' => 'Cuốn sách hướng dẫn học Laravel từ cơ bản đến nâng cao.',
                'language' => 'Tiếng Việt',
                'category_id' => '5',
                'discount_price' => 95000,
                'weight_in_grams' => 450,
                'packaging_size_cm' => '20x14x3',
                'number_of_pages' => 320,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'price' => 350000,
                'image' => 'books/2.jpg',
                'publication_date' => '2020-05-20',
                'description' => 'Hướng dẫn cách viết code sạch, dễ bảo trì và tái sử dụng.',
                'language' => 'English',
                'category_id' => '5',
                'discount_price' => 299000,
                'weight_in_grams' => 600,
                'packaging_size_cm' => '23x15x4',
                'number_of_pages' => 464,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Dế Mèn Phiêu Lưu Ký',
                'author' => 'Tô Hoài',
                'price' => 80000,
                'image' => 'books/19.jpg',
                'publication_date' => '2018-08-10',
                'description' => 'Tác phẩm văn học thiếu nhi nổi tiếng của Việt Nam.',
                'language' => 'Tiếng Việt',
                'category_id' => '8',
                'discount_price' => 65000,
                'weight_in_grams' => 300,
                'packaging_size_cm' => '18x12x2',
                'number_of_pages' => 210,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'price' => 260000,
                'image' => 'books/3.jpg',
                'publication_date' => '2021-01-12',
                'description' => 'Phương pháp thay đổi thói quen nhỏ để đạt kết quả lớn.',
                'language' => 'English',
                'category_id' => '9',
                'discount_price' => 220000,
                'weight_in_grams' => 400,
                'packaging_size_cm' => '21x14x3',
                'number_of_pages' => 320,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Harry Potter và Hòn Đá Phù Thủy',
                'author' => 'J.K. Rowling',
                'price' => 180000,
                'image' => 'books/4.jpg',
                'publication_date' => '2019-09-01',
                'description' => 'Phần đầu tiên trong loạt truyện nổi tiếng Harry Potter.',
                'language' => 'Tiếng Việt',
                'category_id' => '3',
                'discount_price' => 150000,
                'weight_in_grams' => 500,
                'packaging_size_cm' => '22x15x3',
                'number_of_pages' => 350,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Đắc Nhân Tâm',
                'author' => 'Dale Carnegie',
                'price' => 120000,
                'image' => 'books/5.jpg',
                'publication_date' => '2017-04-01',
                'description' => 'Cuốn sách kinh điển về nghệ thuật giao tiếp và ứng xử.',
                'language' => 'Tiếng Việt',
                'category_id' => '9',
                'discount_price' => 100000,
                'weight_in_grams' => 380,
                'packaging_size_cm' => '20x13x2',
                'number_of_pages' => 320,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt, David Thomas',
                'price' => 400000,
                'image' => 'books/6.jpg',
                'publication_date' => '2019-09-13',
                'description' => 'Một trong những cuốn sách lập trình hay nhất mọi thời đại.',
                'language' => 'English',
                'category_id' => '5',
                'discount_price' => 360000,
                'weight_in_grams' => 550,
                'packaging_size_cm' => '23x16x3',
                'number_of_pages' => 352,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                'author' => 'Rosie Nguyễn',
                'price' => 100000,
                'image' => 'books/7.jpg',
                'publication_date' => '2016-07-15',
                'description' => 'Cuốn sách truyền cảm hứng cho thế hệ trẻ Việt Nam.',
                'language' => 'Tiếng Việt',
                'category_id' => '9',
                'discount_price' => 85000,
                'weight_in_grams' => 350,
                'packaging_size_cm' => '19x13x2',
                'number_of_pages' => 280,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Sapiens: Lược Sử Loài Người',
                'author' => 'Yuval Noah Harari',
                'price' => 320000,
                'image' => 'books/8.jpg',
                'publication_date' => '2018-06-05',
                'description' => 'Hành trình phát triển của loài người từ thời nguyên thủy đến hiện đại.',
                'language' => 'Tiếng Việt',
                'category_id' => '6',
                'discount_price' => 280000,
                'weight_in_grams' => 650,
                'packaging_size_cm' => '24x16x3',
                'number_of_pages' => 512,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'price' => 150000,
                'image' => 'books/9.jpg',
                'publication_date' => '2017-09-10',
                'description' => 'Một tiểu thuyết kinh điển phản ánh xã hội toàn trị.',
                'language' => 'English',
                'category_id' => '3',
                'discount_price' => 120000,
                'weight_in_grams' => 420,
                'packaging_size_cm' => '20x14x2',
                'number_of_pages' => 328,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'price' => 180000,
                'image' => 'books/10.jpg',
                'publication_date' => '2015-04-01',
                'description' => 'Một tiểu thuyết kinh điển về công lý và sự phân biệt chủng tộc ở Mỹ.',
                'language' => 'English',
                'category_id' => '3',
                'discount_price' => 150000,
                'weight_in_grams' => 450,
                'packaging_size_cm' => '20x14x3',
                'number_of_pages' => 336,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Think and Grow Rich',
                'author' => 'Napoleon Hill',
                'price' => 200000,
                'image' => 'books/11.jpg',
                'publication_date' => '2016-01-10',
                'description' => 'Cuốn sách về tư duy làm giàu nổi tiếng nhất thế giới.',
                'language' => 'Tiếng Việt',
                'category_id' => '7',
                'discount_price' => 160000,
                'weight_in_grams' => 380,
                'packaging_size_cm' => '21x14x2',
                'number_of_pages' => 400,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Bí Mật Tư Duy Triệu Phú',
                'author' => 'T. Harv Eker',
                'price' => 160000,
                'image' => 'books/13.jpg',
                'publication_date' => '2017-09-25',
                'description' => 'Khám phá sự khác biệt trong tư duy giữa người giàu và người nghèo.',
                'language' => 'Tiếng Việt',
                'category_id' => '7',
                'discount_price' => 130000,
                'weight_in_grams' => 400,
                'packaging_size_cm' => '20x13x2',
                'number_of_pages' => 320,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Sherlock Holmes: Tập 1',
                'author' => 'Arthur Conan Doyle',
                'price' => 140000,
                'image' => 'books/14.jpg',
                'publication_date' => '2018-11-05',
                'description' => 'Tuyển tập truyện trinh thám kinh điển về thám tử Sherlock Holmes.',
                'language' => 'Tiếng Việt',
                'category_id' => '3',
                'discount_price' => 115000,
                'weight_in_grams' => 500,
                'packaging_size_cm' => '22x14x3',
                'number_of_pages' => 420,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Origin',
                'author' => 'Dan Brown',
                'price' => 190000,
                'image' => 'books/15.jpg',
                'publication_date' => '2019-02-18',
                'description' => 'Một tiểu thuyết ly kỳ về khoa học, tôn giáo và sự tiến hóa.',
                'language' => 'English',
                'category_id' => '3',
                'discount_price' => 160000,
                'weight_in_grams' => 600,
                'packaging_size_cm' => '23x15x3',
                'number_of_pages' => 480,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Homo Deus: Lược Sử Tương Lai',
                'author' => 'Yuval Noah Harari',
                'price' => 340000,
                'image' => 'books/16.jpg',
                'publication_date' => '2019-07-07',
                'description' => 'Dự báo về tương lai của loài người trong kỷ nguyên công nghệ.',
                'language' => 'English',
                'category_id' => '5',
                'discount_price' => 300000,
                'weight_in_grams' => 680,
                'packaging_size_cm' => '24x16x3',
                'number_of_pages' => 520,
                'form' => 'Bìa cứng',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'Lược Sử Thời Gian',
                'author' => 'Stephen Hawking',
                'price' => 220000,
                'image' => 'books/17.jpg',
                'publication_date' => '2018-03-10',
                'description' => 'Tác phẩm nổi tiếng về vũ trụ học và những bí ẩn của thời gian.',
                'language' => 'Tiếng Việt',
                'category_id' => '5',
                'discount_price' => 185000,
                'weight_in_grams' => 500,
                'packaging_size_cm' => '22x14x3',
                'number_of_pages' => 350,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
            [
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'price' => 260000,
                'image' => 'books/18.jpg',
                'publication_date' => '2020-01-01',
                'description' => 'Chiến lược khởi nghiệp tinh gọn được áp dụng trên toàn cầu.',
                'language' => 'English',
                'category_id' => '7',
                'discount_price' => 220000,
                'weight_in_grams' => 430,
                'packaging_size_cm' => '21x14x2',
                'number_of_pages' => 336,
                'form' => 'Bìa mềm',
                'state' => 'Còn hàng',
            ],
        ];
        DB::table('books')->insert($books);
    }
}
